### ISSUE TITLE
退出播放視頻未響應

### ISSUE THREAD

**Issue by windy664** [NGoedix/VideoPlayer#1]
![image](https://user-images.githubusercontent.com/81475218/182632043-5befac89-2100-4e06-bb64-372936ad4bed.png)
視頻地址：http://[vd3.bdstatic.com/mda-nh27sy0fsg1dk06g/360p/h264/1659504611709969522/mda-nh27sy0fsg1dk06g.mp4](http://vd3.bdstatic.com/mda-nh27sy0fsg1dk06g/360p/h264/1659504611709969522/mda-nh27sy0fsg1dk06g.mp4)

**Comment by NGoedix** [comment]
Can you send me the game logs?

**Comment by windy664** [comment]
[038月2022 22:26:52.902] [Thread-20/INFO] [FancyVideo-API/]: Dimensions of player minecraft:dynamic/watchvideomod.video_1: 640 | 386
[038月2022 22:26:55.483] [Render thread/INFO] [ModernUI/Core]: Cleanup 233 text layout entries, rehash: false
[038月2022 22:26:55.483] [Render thread/INFO] [ModernUI/Core]: Reloaded text layout engine, res level: 2.0->4.0

**Comment by windy664** [comment]
？？只有一條

**Comment by NGoedix** [comment]
I need all the console logs to know which event is failing.

**Comment by windy664** [comment]
[crash-2022-08-03_22.16.05-client.txt](https://github.com/NGoedix/WatchVideoMod/files/9252284/crash-2022-08-03_22.16.05-client.txt)
[crash-2022-08-03_22.24.45-client.txt](https://github.com/NGoedix/WatchVideoMod/files/9252285/crash-2022-08-03_22.24.45-client.txt)
自從加了這個mod后，每次啓動游戲都會提示這個

**Comment by windy664** [comment]
[debug.log](https://github.com/NGoedix/WatchVideoMod/files/9252296/debug.log)
我不知道哪個是日志，應該是這個吧？

**Comment by NGoedix** [comment]
I think I understand what the problem is, I had not uploaded the version that error was fixed. You will have it as soon as it is validated by curseforge.
