### ISSUE TITLE
Mod doesn't work in 1.16.5 version

### ISSUE THREAD

**Issue by martinuxp** [NGoedix/VideoPlayer#10]
Agregue el mod a mi server pero al intentar iniciarlo el server crasheo.
[](url)
[crash-2023-04-08_21.43.52-fml.txt](https://github.com/NGoedix/WatchVideoMod/files/11184291/crash-2023-04-08_21.43.52-fml.txt)

**Comment by NGoedix** [comment]
Use this FVA (Fancy-Video API) version in the 1.16.5: https://mega.nz/file/CvxzzZpZ#JuGN4EXBa8dJCm2bBJg-ehJ0hLJhfW3mdLUoeO8rIx4
