### ISSUE TITLE
Video plays with inventory gui in front of everything

### ISSUE THREAD

**Issue by JAVIxcr** [NGoedix/VideoPlayer#14]
I leave a pictures that can describe what is happening
![image](https://github.com/NGoedix/WatchVideoMod/assets/124131949/3e9623e4-d543-4113-b502-7ae6e51505ab)

**Comment by NGoedix** [comment]
Will be fixed in the new version

**Comment by JAVIxcr** [comment]
I forgot to say, this is the 1.16.5 Forge 36.2.34

**Comment by NGoedix** [comment]
Oh, then it will be fixed when te API is ready for the 1.16.5
