### ISSUE TITLE
When video plays, shows frozen screen of the example video.

### ISSUE THREAD

**Issue by ajaymds** [NGoedix/VideoPlayer#15]
Hi. I'm trying to play a video but when I do, It just shows this picture

![SharedScreenshot1](https://github.com/NGoedix/WatchVideoMod/assets/26396343/0dd8192f-1d5e-4095-b35d-a7c33cbb3df3)

It might be, because it is a YouTube video.

If that is the problem is there any other Websites other then commondatastorage that I can play it from?

**Comment by NGoedix** [comment]
I am working in the new API, wait a few days please and it will be available.
