### ISSUE TITLE
Server (1.18) complains about water media being on server

### ISSUE THREAD

**Issue by netcore10** [NGoedix/VideoPlayer#17]
but when you remove watermedia the server won't launch because it needs it.

**Comment by netcore10** [comment]
[2023-06-12-7.log](https://github.com/NGoedix/WatchVideoMod/files/11728325/2023-06-12-7.log)

then of course when i remove it, video player fails due to watermedia dependency on server

**Comment by NGoedix** [comment]
I will fix it in the 2.0.2, thanks

**Comment by NGoedix** [comment]
Will be fixed in the API finally

**Comment by netcore10** [comment]
After the update i get a crash on client when running /playvideo 
[crash-2023-06-13_00.05.52-client.txt](https://github.com/NGoedix/WatchVideoMod/files/11735406/crash-2023-06-13_00.05.52-client.txt)
https://paste.atlauncher.com/view/936ddbf0-8e1a-474d-aafe-86d0d216a266

There was a line of "Vlc component is not loaded"

**Comment by NGoedix** [comment]
Can you try only with watermedia and videoplayer?

**Comment by netcore10** [comment]
it's kinda hard to test properly due to it happening at random, but it seems i'm stuck on this problem - it happens at random

**Comment by netcore10** [comment]
could it be sodium?

**Comment by netcore10** [comment]
it does indeed just happen with videoplayer and watermedia https://paste.atlauncher.com/view/f3fd9a35-0e88-483f-a705-348a9122ad1c

**Comment by NGoedix** [comment]
I told only videoplayer and watermedia, no more mods (against the fabric api)

**Comment by NGoedix** [comment]
And can you try in forge too?

**Comment by netcore10** [comment]
oops wrong log, really sorry! it crashes with just those 2,

https://paste.atlauncher.com/view/f0a15920-badb-48dd-b455-5199d159b5c9

forge doesn't crash

**Comment by NGoedix** [comment]
Check if fixed

**Comment by netcore10** [comment]
It still crashed https://paste.atlauncher.com/view/cf7fefec-6b48-4dfb-974a-2994221a8e83

**Comment by NGoedix** [comment]
You must use the latest version of watermedia

**Comment by netcore10** [comment]
Apologies, my mod loader took a while to update the mod listing. i got this https://paste.atlauncher.com/view/b9397a4e-a047-4813-8453-735ac43b54eb 
![image](https://github.com/NGoedix/WatchVideoMod/assets/181536/913e6011-3f9a-4300-89a5-51166d1a4cd8)

**Comment by NGoedix** [comment]
Can you only use VideoPlayer with watermedia and try to play a video in a new world? To avoid other mod information

**Comment by netcore10** [comment]
of course, here you go: I crashed, it worked for 2 seconds https://paste.atlauncher.com/view/83bba8e6-2c78-4fff-819e-b92079d132e0

**Comment by netcore10** [comment]
could it be sodium optimisation causing vlc to not load too?

**Comment by netcore10** [comment]
I tested on 1.19.2 and it works, but 1.18.2 can't find vlc for some reason in some setups

**Comment by NGoedix** [comment]
Can you try to remove the .minecraft/cache folder and open again minecraft?

**Comment by netcore10** [comment]
It didn't crash but i got failed to load vlc in 1.18 again, the logs don't have much to go on except repeating that it can't find vlc. 1.19 worked.

**Comment by NGoedix** [comment]
Can you send the debug.log and the crash?

**Comment by netcore10** [comment]
I can't quite find the crash i had, but is this the log you wanted? (1.18) 
[vlc.log](https://github.com/NGoedix/WatchVideoMod/files/11826295/vlc.log)
[latest.log](https://github.com/NGoedix/WatchVideoMod/files/11826296/latest.log)

**Comment by NGoedix** [comment]
The debug.log please, not the latest.log

**Comment by netcore10** [comment]
i can't seem to find the location of debug.log.

**Comment by NGoedix** [comment]
discord to get support please.
