### ISSUE TITLE
How to get video link with the format .mp4

### ISSUE THREAD

**Issue by SASKERR** [NGoedix/VideoPlayer#2]
hello! I have a question, how do I get a link like the example of the video that I want, since with another type of link it is impossible

**Comment by NGoedix** [comment]
I am currently working on that but meanwhile you can use an online hosting (ie: 000webhost)

**Comment by NGoedix** [comment]
I am currently working on that but meanwhile hoy can use an online hosting (ie: 000webhost)

**Comment by SASKERR** [comment]
Hi, I looked for how to use 000webhost but I really didn't understand how to get the link of a video on this page, I tried with google drive but as I said before it doesn't play anything in the game, how could I get a link like the one in the description of the game mod?

**Comment by NGoedix** [comment]
You need a hosting service to store the mp4 file, for example, 000webhosting, Biz.nf, etc...

**Comment by JhonasBY** [comment]
Hola, subiendo el video a discord  y copiando su enlace funciona muy bien

**Comment by NGoedix** [comment]
Yes, discord stores it on their server and copying the link copies the direct link to the video.

**Comment by DariMayu** [comment]
Hello, sorry, how could you get the link of the video from 000website

**Comment by eonsito** [comment]
> Hola, subiendo el video una discordia y copiando su encaje funciona muy bien

How do you copy the link of the video?

**Comment by NGoedix** [comment]
Right Click -> Copy link
