### ISSUE TITLE
Game unable to launch with WATERMeDIA API

### ISSUE THREAD

**Issue by DEAFG0AT** [NGoedix/VideoPlayer#21]
Here's the crash report I get when launching:
https://bytebin.lucko.me/7JhIxzuDob

I posted the bug to the WATERMeDIA's Git, and the author had this to say

![image](https://github.com/NGoedix/WatchVideoMod/assets/104733108/cc24572d-0cac-4c63-acbc-2b57b8211001)

If this is truly the case, you will have to drop Fabric support for your mod as well

**Comment by SrRapero720** [comment]
probably you didn't notice, but ngoedix is also an author of watermedia.

**Comment by DEAFG0AT** [comment]
I noticed

**Comment by SrRapero720** [comment]
fabric support is back
wait until was updated to 2.0.0 api

**Comment by DEAFG0AT** [comment]
I'm still getting this crash - 

[crash-2023-08-29_20.23.22-client.txt](https://github.com/NGoedix/WatchVideoMod/files/12471404/crash-2023-08-29_20.23.22-client.txt)

**Comment by NGoedix** [comment]
The mod was not updated yet to watermedia 2.0.0

**Comment by NGoedix** [comment]
Solved in the new update.
