### ISSUE TITLE
Crash 1.19.2 on quilt

### ISSUE THREAD

**Issue by netcore10** [NGoedix/VideoPlayer#23]
I switched over to quilt, it's a fork of fabric, but it seemed to crash when launching a video
https://paste.atlauncher.com/view/c26ec932-fe7e-4670-8477-f7f4b8da996f

**Comment by SrRapero720** [comment]
quilt wasn't supported by WATERMeDIA.

**Comment by SrRapero720** [comment]
wait, i read your logs... literally watermedia loads perfectly on quilt what the heck?

**Comment by SrRapero720** [comment]
sorry for my late response
you need to use WATERMeDIA 1.2.x instead of 1.3.x
