### ISSUE TITLE
Crash when playing video

### ISSUE THREAD

**Issue by eldediamante** [NGoedix/VideoPlayer#24]
Watermedia git ticket: [#15](https://github.com/SrRapero720/watermedia/issues/15#issue-1827651364)
- ESP 
```
- Entro al server.
- Ejecuto el comando: "/playvideo @a 50 https://youtu.be/lIe4VHXpftg"
- Y crashea (Cierre completo del minecraft) 
```
- ENG 
```
- I enter the server.
- I run the command: "/playvideo @a 50 https://youtu.be/lIe4VHXpftg"
- And it crashes (Complete closure of minecraft)
```
Version Minecraft: Forge - 40.2.10 -> **1.18.2**
Version Mod: 1.2.0 - 1.2.16 - 1.3.0 - 1.3.20 - 1.3.22 - 1.3.23
And "Video Player mod": [2.20](https://www.curseforge.com/minecraft/mc-mods/video-player/files/4628952)
Error:
![imagen_2023-07-30_074540325](https://github.com/NGoedix/WatchVideoMod/assets/55103304/badfc4f8-b2a3-464b-a51b-44c10b626e86)

Crash log: [crash-2023-07-29_22.29.29-client.txt](https://github.com/SrRapero720/watermedia/files/12207937/crash-2023-07-29_22.29.29-client.txt)

**Comment by eldediamante** [comment]
- ESP
-- [Solución](https://discord.com/channels/1074342886008705065/1074342886386188411/1135321899652612107) (Solo 1.18.X)

- ENG
-- [Solution](https://discord.com/channels/1074342886008705065/1074342886386188411/1135321899652612107) (Only 1.18.X)

**Comment by SrRapero720** [comment]
Issue wasn't solved, please REOPEN IT

**Comment by eldediamante** [comment]
- **ESP** 
-- A mi si me solucionó, pero te lo abro igualmente
- **ENG**
-- It did solve it for me, but I'll open it for you anyway

**Comment by MamohoReloaded** [comment]
> * **ESP**
>       -- A mi si me solucionó, pero te lo abro igualmente
> 
>     * **ENG**
>       -- It did solve it for me, but I'll open it for you anyway

como lo solucionaste? los links de discord que proporcionaste no funcionan

**Comment by SrRapero720** [comment]
you must join to Goedix discord to use these links
BTW issue still exists on OFFICIAL releases and source code, my PR is just a workarround but nothing official.
