### ISSUE TITLE
The game crashes when playing a video

### ISSUE THREAD

**Issue by ZailenZ** [NGoedix/VideoPlayer#27]
![err](https://github.com/NGoedix/WatchVideoMod/assets/126627023/3de49595-5f19-4f35-8373-3c248372fd55)

I enter the world or server, execute the command: /playvideo ZailenZ 50 http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
And the game closes.

I tried it with the following versions: Minecraft 1.20.1-forge-47.1.0 | Minecraft 1.20.1-forge-47.1.43 | Minecraft 1.20.1-forge-47.1.44
Mods versions: VideoPlayer-2.0.3-FORGE-1.20.X and WATERMeDIA/1.3.35
And I still have the same error.

Minecraft 1.20.1-forge-47.1.44:
[crash-2023-08-14_14.41.01-client.txt](https://github.com/NGoedix/WatchVideoMod/files/12339057/crash-2023-08-14_14.41.01-client.txt)

Minecraft 1.20.1-forge-47.1.43:
[crash-2023-08-14_14.39.04-client.txt](https://github.com/NGoedix/WatchVideoMod/files/12339053/crash-2023-08-14_14.39.04-client.txt)

Minecraft 1.20.1-forge-47.1.0:
[crash-2023-08-14_14.39.58-client.txt](https://github.com/NGoedix/WatchVideoMod/files/12339055/crash-2023-08-14_14.39.58-client.txt)

I hope I can get some help ^_^

**Comment by norfair00** [comment]
Only WATERMeDIA 1.2.16
https://legacy.curseforge.com/minecraft/mc-mods/watermedia/files/4607766
