### ISSUE TITLE
The game crash after less than 1 minute of video

### ISSUE THREAD

**Issue by EnricoVvV** [NGoedix/VideoPlayer#29]
Hi, I'm having a problem with videplayer2.0.3+watermedia1.2.16: the game crash after less than 1 minute of video

How can I solve?

https://pastebin.com/0KEpsnZ6

**Comment by SrRapero720** [comment]
please wait until update was released
1.19.2 is still pending

**Comment by EnricoVvV** [comment]
Ok thanks I'll wait, what would be a possible date if there was one?

**Comment by NGoedix** [comment]
Solved in the new update
