### ISSUE TITLE
Mod not loading properly (1.19.4)

### ISSUE THREAD

**Issue by vYuri** [NGoedix/VideoPlayer#31]
Hello there, I've been trying to use the last version of the 1.19.4 release and for some reason it won't work properly.

When playing the example url nothing will be playing. The player freezes but no image is showing. Any ideas of what could be wrong?

Edit: Version is actually 2.0.3 Forge.
Since the 2.5.2 Version is actually not working on Forge.

I'm getting this when it is on the folder mod:
![image](https://github.com/NGoedix/WatchVideoMod/assets/8495969/d0088ef5-2753-4478-ab8e-a84ade7e3438)

and not even able to join to servers because of this

**Comment by NGoedix** [comment]
Can you give more information? Url that you are trying to play and debug.log file

**Comment by vYuri** [comment]
Well... I am sorry to say this but it actually had to do with the watermedia mod since it wasn't updated correctly on modrinth and had to use an old version. Sorry and thanks anyways for responding so quick!
