### ISSUE TITLE
Minecraft GUI and Chat pixelated after playing a video

### ISSUE THREAD

**Issue by vYuri** [NGoedix/VideoPlayer#33]
After a video finishes playing, my minecraft looks pixelated 

You can compare on the images how text looks and how images are not pixelated. Is it possible to fix this?
Chat also looks pixelated as you can see

![image](https://github.com/NGoedix/WatchVideoMod/assets/8495969/294ea655-70dc-4923-ab1a-4dfe431debd1)

![image](https://github.com/NGoedix/WatchVideoMod/assets/8495969/9e99a9ff-6d9d-42fc-b3bb-4fc2b160a68f)

**Comment by NGoedix** [comment]
I will check it

**Comment by NovaXCIV** [comment]
![image](https://github.com/NGoedix/WatchVideoMod/assets/104044556/87821b7f-13e6-4263-977a-15e417f73e8f)

It also happens to me. Forge 1.19.2

**Comment by NGoedix** [comment]
using shaders / optifine / rubidium?

**Comment by NGoedix** [comment]
And playing with command or tv?

**Comment by NovaXCIV** [comment]
TV works fine. The problem is via command. I use Rubidium & Extras + Oculus

**Comment by NGoedix** [comment]
We are currently not supporting shaders due to the obvious incompatibility, but that does not mean that we are working to fix it.

**Comment by NovaXCIV** [comment]
Understood, thank you. Also, I found another bug and I don't know if it is the fault of the latest Watermedia update:
Sidebands appear after the latest update of Watermedia (which also become larger depending on the video).
_*tested with the previous version of Watermedia and they are not there (I'm full screen 16:9)._

![image](https://github.com/SrRapero720/watermedia/assets/104044556/1c7eec3e-dd15-42e4-bb27-d6cdc65730c3)

**Comment by NGoedix** [comment]
I recently released an update that took into account the aspect ratio of the videos, otherwise they would be stretched and some would look deformed

**Comment by NGoedix** [comment]
But maybe i can add an option to force disable it on the command

**Comment by NovaXCIV** [comment]
The fact is that it works perfectly with the previous Watermedia update; I thought that was the problem.

**Comment by NGoedix** [comment]
Some videos with specific aspect ratio like 4:3 looks deformed, i don't know why with an older watermedia version it shows resized (depends only on VideoPlayer), but I will check it.
Tecnically is not a bug or a problem, is the aspect ratio support, but I will add an option to cancel the resize in the next update (3.0).
Thanks!

**Comment by NovaXCIV** [comment]
I think it's better a command to activate the "resize". So if someone sees the video stretched, will use the command, otherwise, it works great as always. Thanks!

**Comment by NGoedix** [comment]
The player really now works like any player, adapting the size to the aspect ratio of the video, the same thing Youtube does, for example when you have a 4:3 video (through which we found the problem), add an option to disable the aspect ratio It is something we will do (thanks to your comment), but the ideal is that it be activated by default since all players have it that way, but don't worry, for 3.0 there will be the option in the command to know if you want it or not managing the aspect ratio.

**Comment by NGoedix** [comment]
I don't have the problem on my machine, but I will add the option in the 3.0
