### ISSUE TITLE
Client crash (server side is fine) after playing a video

### ISSUE THREAD

**Issue by NovaXCIV** [NGoedix/VideoPlayer#36]
Forge 1.19.2. Logs: https://pastebin.com/vrv1X4cX

**Comment by NovaXCIV** [comment]
+If you run 2 videos at the same time, it crashes the client. You could make that when you switch to another video you stop the previous one first to the target players, to avoid the problem.

**Comment by NGoedix** [comment]
I will check it

**Comment by NovaXCIV** [comment]
Hello, do you have any ETA for the new update? For the resize update too.

**Comment by NGoedix** [comment]
No, but maybe in a month, I want to finish the fabric version and then work on the 3.0 fixing bugs, refactoring code and adding more blocks and items.

**Comment by NovaXCIV** [comment]
Got it. I hope soon, as I'm planning something big in these weeks, and your mod it's a god savior for content.
 And obv without pressure. It's your work and time. 🙌
 
 Another suggestion as items, could be a custom itemframe with the GUI as the TV, and you can set X,Y ecc.. to create for example a cinema.

**Comment by NGoedix** [comment]
Thanks for the support! If you want an item to do that, you can check waterframes, I don't have planned to add it at the moment

**Comment by NovaXCIV** [comment]
Gotcha and np. The only problem with Waterframes is the incompatibility with Watermedia 2.0+. And if I have to decide, I pick videoplayer.

**Comment by NGoedix** [comment]
Solved in the new version
