### ISSUE TITLE
Game crashes after entering the /playvideo command

### ISSUE THREAD

**Issue by DEAFG0AT** [NGoedix/VideoPlayer#38]
**Game Version:** 1.19.2
**Mod Version:** 2.0.3
**WaterMedia Version:** 2.0.10

**Crash Report:**

[crash-2023-11-05_16.18.38-client.txt](https://github.com/NGoedix/VideoPlayer/files/13261257/crash-2023-11-05_16.18.38-client.txt)

**Video**:

https://github.com/NGoedix/VideoPlayer/assets/104733108/1abda72c-f567-4a72-a44e-879a0160ea25

**Comment by NGoedix** [comment]
VideoPlayer fabric version uses watermedia 1.2.16, i am working on the new update
