### ISSUE TITLE
Forge 1.20.1 - Game crashes when placing TV in singleplayer

### ISSUE THREAD

**Issue by foggydawg** [NGoedix/VideoPlayer#39]
Minecraft: 1.20.1
Forge: 47.2.0
WaterMedia: 2.0.12
VideoPlayer: 2.6
OS: Windows 10 Pro 64bit

Expected behavior: BlockEntity is placed and usable.
Actual behavior: As soon as I right-click to place the TV on the ground, the game crashes. The game will crash again when attempting to reload that save.

Info: Does not occur on my Linux machine, TV BlockEntity can be placed and used with YouTube link just fine.

[crash-2023-11-11_16.55.35-client.txt](https://github.com/NGoedix/VideoPlayer/files/13326807/crash-2023-11-11_16.55.35-client.txt)

**Comment by foggydawg** [comment]
Downgrading to WaterMedia 2.0.10 stops the crash and TV works as intended.

**Comment by NGoedix** [comment]
I will check it, thanks!

**Comment by NGoedix** [comment]
Fixed on 3.0.1 (available on modrinth)
