### ISSUE TITLE
Constant crash with video player on multiplayer

### ISSUE THREAD

**Issue by Fonazo15** [NGoedix/VideoPlayer#43]
It happens at random, but it's not rare.
And when you try to re-log, it's an instant crash.
[crash-2024-02-26_16.18.44-client.txt](https://github.com/NGoedix/VideoPlayer/files/14410081/crash-2024-02-26_16.18.44-client.txt)

**Comment by NGoedix** [comment]
Fixed on 3.0.1 (available on modrinth)
