### ISSUE TITLE
Crash when playing video on tv

### ISSUE THREAD

**Issue by Poke5555** [NGoedix/VideoPlayer#44]
Sometimes when i place a TV and play a video my game and others around me will crash, the played video doesnt seem to matter.
if you need any more info let me know

Forge 47.2.0
VideoPlayer-2.6.2-FORGE-1.20.X
watermedia-2.0.28

[crash-2024-04-08_12.55.21-client.txt](https://github.com/NGoedix/VideoPlayer/files/14909047/crash-2024-04-08_12.55.21-client.txt)

**Comment by NGoedix** [comment]
Fixed on 3.0.1 (available on modrinth)
