### ISSUE TITLE
Crash on /playvideo with latest WaterMedia versions (1.20.1)

### ISSUE THREAD

**Issue by BrangGit** [NGoedix/VideoPlayer#46]
Hi there !

/playvideo command makes the game crash, with this error : 

```java
java.lang.NoSuchMethodError: 'int me.srrapero720.watermedia.api.WaterMediaAPI.math_colorARGB(int, int, int, int)'
	at com.github.NGoedix.watchvideo.client.gui.VideoScreen.renderBlackBackground(VideoScreen.java:182) ~[VideoPlayer-2.6.2-FORGE-1.20.X.jar%23161!/:?]
```

Tested in singleplayer
Minecraft Version : 1.20.1
VideoPlayer version : 2.6.2
WaterFrames version : 2.0.44

Crash report : https://mclo.gs/J7BwPmX / [crash-2024-05-10_12.30.52-client.txt](https://github.com/NGoedix/VideoPlayer/files/15273883/crash-2024-05-10_12.30.52-client.txt)

**Comment by NGoedix** [comment]
Fixed on 3.0.1 (available on modrinth)
