### ISSUE TITLE
Clicking Save causes a crash to the desktop

### ISSUE THREAD

**Issue by w774431242** [NGoedix/VideoPlayer#47]
Behavior:
Step 1 Place "TV"
Step 2. Insert "URL" into the local file to play "local://F:\TG\bs\ Bs-1.mp4"
Step 3. An Crash To Desktop  is reported after clicking the "SAVE" button.
Step 4. Re-enter the game archive, "TV" is playing the local video
To change the local video address, repeat steps 2-4. -- [Translator]
##Why is there an error? Please tell me. Thank you

Modlist：
Minecraft:1.20.1
video player:2.6.2
watermedia:2.0.51

[minecraft-exported-logs-2024-05-13T21-46-12.log](https://github.com/NGoedix/VideoPlayer/files/15295353/minecraft-exported-logs-2024-05-13T21-46-12.log)

**Comment by NGoedix** [comment]
Fixed on 3.0.1 (available on modrinth)
