### ISSUE TITLE
Playing Two videos causes crash

### ISSUE THREAD

**Issue by this-dude-codes** [NGoedix/VideoPlayer#48]
Using the /playvideo command on a command block plays the video, but when another command block executes a /playvideo command a few seconds after, everything lags and the game crashes.
1.19.2 Forge

**Comment by NGoedix** [comment]
Logs please

**Comment by this-dude-codes** [comment]
[latest.log](https://github.com/NGoedix/VideoPlayer/files/15409715/latest.log)
here you go!

**Comment by NGoedix** [comment]
I will check it!

**Comment by NGoedix** [comment]
Can you try the version 3.0.1? Available on modrinth
