### ISSUE TITLE
[Suggestion] An ability to play local files

### ISSUE THREAD

**Issue by yellowcake3d** [NGoedix/VideoPlayer#51]
As title says, it would be nice for modpack devs to be able to play local files from the .minecraft folder at least, to not rely on a modpack player to have an internet connection when they play the modpack. For example to be able to pack a small video in, let's say, "config/videos/" folder and then play it either with playvideo command or a tv.

**Comment by NGoedix** [comment]
Have you tried `minecraft://`, `file://` or `local://`?

**Comment by yellowcake3d** [comment]
Ah, so that's the formatting, in that case this feature already exists and the command /playvideo local://config/video.mp4 would play a video from a config folder named video.mp4

Thanks for the help, this is an amazing mod!

**Comment by StickyChannel92** [comment]
**I tested it and the best way to get the URL is to drag the file to your browser as a new tab, then copy the URL that says "file:///X:/<videopath>/video.mp4" and paste it into the command like this:**
**`/playvideo @s 10 file:///X:/<videopath>/video.mp4`**

That is the best way to get the full pathname if you don't have any third party tools that can copy the path for you, like Everything Search and Directory Opus. However, I couldn't get it to work on the mod's included TV. Pasting in the same link does not function, although a YouTube video does.

Can you play local videos on a TV and local music on a Radio (blocks you place in-game)?
