### ISSUE TITLE
[1.16.5] Mod Loading Failed

### ISSUE THREAD

**Issue by 301haru** [NGoedix/VideoPlayer#6]
VideoPlayer Version : 0.4
FancyVideo API Version : 0.1.0.0 , 0.1.1.1 (both)

[crash-2022-10-24_03.01.55-fml.txt](https://github.com/NGoedix/WatchVideoMod/files/9847207/crash-2022-10-24_03.01.55-fml.txt)

**Comment by NGoedix** [comment]
Use this API: https://mega.nz/file/CvxzzZpZ#JuGN4EXBa8dJCm2bBJg-ehJ0hLJhfW3mdLUoeO8rIx4
