### ISSUE TITLE
No puedo reproducir un video de un servidor web

### ISSUE THREAD

**Issue by ThisIsPlayron** [NGoedix/VideoPlayer#8]
He subido a un servidor WEB este video: http://elcairo.rf.gd/pato.mp4
Y no lo reproduce

**Comment by NGoedix** [comment]
¿Podrías proporcionar logs y un vídeo de prueba de concepto del uso del mod?

**Comment by NGoedix** [comment]
Debido a que ya te funciona (comentado en discord) cierro la issue.
